### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by iamsalnikov** [rudart/dart.rocks#3]
We use the mongodb as a data storage. 

App configuration for connection:

``` yaml
db:
    host: <db.host>
    port: <db.port>
    username: <db.username>
    password: <db.password>
```

Application container must be configurable by following parameters:

```
DB_HOST
DB_PORT
DB_USERNAME
DB_PASSWORD
```

I will use  [package "objectory"](https://github.com/vadimtsushko/objectory) for work with database.
